Vagrant.configure("2") do |config|
  config.vm.box = "ferventcoder/win-xpsp3-x86-en"
  config.vm.hostname = "winxp-saab"
  config.vm.communicator = "winrm"
  config.vm.network "private_network", ip: "192.168.56.72"
  config.vm.synced_folder "../../vendor", "/vendor", type: "virtualbox"
  config.vm.provider "virtualbox" do |vb|
    vb.name = "winxp-saab"
    vb.memory = 1024
    vb.cpus = 1
    vb.customize ["modifyvm", :id, "--usb", "on"]
  end
  config.vm.provision "shell", path: "provision.ps1"
end
