"""IUdsClient -- ISO 14229 UDS client."""

from __future__ import annotations

from typing import Protocol

from saab_suite.kernel.types import WirePayload


class IUdsClient(Protocol):
    """High-level UDS client over an ISO-TP transport."""

    def diagnostic_session_control(self, session_type: int) -> WirePayload: ...
    def ecu_reset(self, reset_type: int) -> WirePayload: ...
    def security_access(self, level: int, key: WirePayload | None = None) -> WirePayload: ...
    def read_data_by_identifier(self, did: int) -> WirePayload: ...
    def write_data_by_identifier(self, did: int, data: WirePayload) -> WirePayload: ...
    def read_dtc_information(self, sub_function: int, status_mask: int = 0xFF) -> WirePayload: ...
    def clear_diagnostic_information(self, group: int = 0xFFFFFF) -> WirePayload: ...
    def request_download(self, address: int, size: int) -> WirePayload: ...
    def transfer_data(self, block_seq_counter: int, data: WirePayload) -> WirePayload: ...
    def request_transfer_exit(self) -> WirePayload: ...
    def routine_control(self, sub_function: int, routine_id: int, data: WirePayload = b"") -> WirePayload: ...
    def tester_present(self, suppress_response: bool = True) -> WirePayload: ...
