Vagrant.configure("2") do |config|
  config.vm.box = "gusztavvargadr/windows-7"
  config.vm.hostname = "win7-saab"
  config.vm.communicator = "winrm"
  config.vm.network "private_network", ip: "192.168.56.71"
  config.vm.synced_folder "../../vendor", "/vendor", type: "virtualbox"
  config.vm.provider "virtualbox" do |vb|
    vb.name = "win7-saab"
    vb.memory = 4096
    vb.cpus = 2
    vb.customize ["modifyvm", :id, "--usb", "on"]
    vb.customize ["modifyvm", :id, "--usbehci", "on"]
  end
  config.vm.provision "shell", path: "provision.ps1"
end
