"""IFlashTarget -- abstract ECU flash target."""

from __future__ import annotations

from typing import TYPE_CHECKING, Protocol

if TYPE_CHECKING:
    from saab_suite.domain.firmware.image import FirmwareImage


class IFlashTarget(Protocol):
    """An ECU family that can be programmed."""

    @property
    def family(self) -> str: ...
    def enter_programming_mode(self) -> None: ...
    def authenticate(self) -> None: ...
    def erase(self, region_start: int, region_end: int) -> None: ...
    def transfer(self, image: FirmwareImage) -> None: ...
    def verify(self, image: FirmwareImage) -> bool: ...
    def finalize(self) -> None: ...
