"""IKwpClient -- ISO 14230 KWP2000 client (legacy modules)."""

from __future__ import annotations

from typing import TYPE_CHECKING, Protocol

if TYPE_CHECKING:
    from saab_suite.kernel.types import WirePayload


class IKwpClient(Protocol):
    """KWP2000 client for older 9-3 / 9-5 modules."""

    def start_diagnostic_session(self, session_type: int) -> WirePayload: ...
    def stop_diagnostic_session(self) -> WirePayload: ...
    def read_dtc_by_status(self, status: int = 0x00) -> WirePayload: ...
    def clear_diagnostic_information(self, group: int = 0xFF00) -> WirePayload: ...
    def read_data_by_local_id(self, local_id: int) -> WirePayload: ...
    def tester_present(self, suppress_response: bool = True) -> WirePayload: ...
