#!/bin/sh
HERE="$(dirname "$(readlink -f "${0}")")"
export PATH="${HERE}/usr/bin:${PATH}"
export PYTHONHOME="${HERE}/usr"
export PYTHONPATH="${HERE}/usr/lib/python3.11/site-packages"
exec "${HERE}/usr/bin/python3" -m saab_suite.interfaces.cli.main "$@"
